### ISSUE TITLE
Templates for component addons

### ISSUE THREAD

**Issue by MarkMT** [ember-cli/ember-cli.github.io#100]
The guide for creating addons is clear about where a component's javascript should go (`addon/components/my-component.js`) and how to import that to the consuming app via `app/components/my-component.js`. However it seems to be silent on the issue of where the template file goes and how it is made accessible to the consuming app. Although it's not stated, it seems reasonable to suppose that the template can go in `app/templates/components/my-component.hbs`, yet when I look at a number of publicly available component addons I see some other approaches in use.

Some seem to put the template in `addons/templates/components`, import it as `layout` in `addon/components/my-component.js` and use the `layout` property in the `Component` subclass, but my impression is that this is a deprecated feature.

I've also seen some with the template in `addons/templates/components` which is then imported by a _javascript_ file in `app/templates/components`.

This seems to be an area in which a more clearly defined convention is needed and I would like to suggest that some additional guidance be added to https://ember-cli.com/extending/#addon-components.

**Comment by MarkMT** [comment]
Playing with this a little more, I realized I can `ember g component` inside the addon and get the skeleton files created. When I do that, the template is in `addon/templates/components` while in `addon/components/my-component.js` we have this:

```
import Ember from 'ember';
import layout from '../templates/components/my-component';

export default Ember.Component.extend({
  layout
});
```

This usage of `layout` doesn't seem to be documented in any guides (in examples in the wild I've seen both this approach and `layout: layout` in the subclass) but if I'm not mistaken this uses a feature of the deprecated `Ember.View`. Perhaps the component generator needs updating, but in any case I still think some guidance is needed in https://ember-cli.com/extending/#addon-components.

**Comment by mike-north** [comment]
The default value of the **layout** property is whatever module is found via the usual name-matching convention in the `app/components/templates/` folder.

The default component blueprint just overrides this and loads a template of a particular name. You could rename the template (and the corresponding import) to whatever you like and it would still work just as you would expect.

The benefit of having templates in the addon tree is that you end up making the internals of your addon a bit more private. They won't show up in the ember inspector like this
<img width="609" alt="screen_shot_2016-10-29_at_6_57_38_pm" src="https://cloud.githubusercontent.com/assets/558005/19831416/9d892966-9e09-11e6-9c28-bac0e5631875.png">
and consumers won't be able to do weird stuff like using the component templates as partials

``` hbs
{{!-- Won't work if addon component templates are in the addon tree --}}
{{partial 'components/my-component'}}
```

**Comment by MarkMT** [comment]
Thanks @mike-north. That mostly makes sense and I like the idea of keeping the template in `addon`.

I'm guessing that `layout` the way it's used here is a syntactic shortcut for `layout: layout` which I've seen elsewhere and makes sense to me? Is that usage documented somewhere? Or am I misunderstanding? 

Also am I right that `layout` is deprecated along with the rest of the `Ember.View` API? That aside, I think my concern about the lack of clarity about component templates in the ember-cli guide remains valid. I'm happy to suggest some text, but I'm sure there are others who understand all of this much better than me.

**Comment by mike-north** [comment]
> I'm guessing that layout the way it's used here is a syntactic shortcut for layout: layout which I've seen elsewhere and makes sense to me? Is that usage documented somewhere? Or am I misunderstanding?

Correct. This is an ES2015 feature called [enhanced object literals](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=var%20layout%20%3D%20%22hello%22%3B%0A%0Avar%20myThing%20%3D%20%7B%0A%20%20layout%0A%7D%3B) ([example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=var%20layout%20%3D%20%22hello%22%3B%0A%0Avar%20myThing%20%3D%20%7B%0A%20%20layout%0A%7D%3B)). The only place you might find a path to content on this topic in the documentation is when the guides provide links to information on ES2015 features [here](https://guides.emberjs.com/v2.9.0/getting-started/quick-start/#toc_define-a-route).

> Also am I right that layout is deprecated along with the rest of the Ember.View API?

The use of this [`layout` attribute in Ember.Component](https://github.com/emberjs/ember.js/blob/v2.9.0/packages/ember-htmlbars/lib/component.js#L158) is a little different than [the Ember.View concept you're referring to](http://emberjs.com/api/classes/Ember.View.html#toc_layouts).

**Comment by mike-north** [comment]
> I think my concern about the lack of clarity about component templates in the ember-cli guide remains valid. 

Totally agree on this point. I can't even find an indication in the API docs or guides that `Ember.Component#layout` is part of the public API surface. I have created an issue for you (https://github.com/emberjs/ember.js/issues/14548) to track this totally legitimate aspect of the problem (the confusion on your part)

**Comment by MarkMT** [comment]
Thanks, much appreciated.

**Comment by nathanhammond** [comment]
We should also capture some content on the Ember CLI side. If you include a template in the addon folder it _must_ be imported as `layout` otherwise it will not be resolved by Ember's resolver. You must also move `ember-cli-htmlbars` into the `dependencies` section of the addon's `package.json`. Those two pieces of information would definitely be worth capturing.

@MarkMT You've now learned a lot on this topic: would you be willing to write a paragraph to add to [the section about the resolver](https://ember-cli.com/user-guide/#using-modules) and open a PR?

**Comment by MarkMT** [comment]
Sure I'll give it a go in the next few days.

**Comment by sumeetattree** [comment]
I just ran into this issue. Couldn't find any info in the docs on how to handle this. I was trying to use a template only component but the application wouldn't find it, I suspect this is because it's not getting included.
