### ISSUE TITLE
Add documentation for addons blacklist/whitelist options

### ISSUE THREAD

**Issue by kfoisy** [ember-cli/ember-cli.github.io#103]
The EmberApp constructor seems to allow addon.blacklist and addon.whitelist options (see https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L404) that exclude or include addons defined in your app's package.json file when building your app. These configuration options should be documented.

As a side note, I've found these options useful for excluding dependencies from my fastboot builds that aren't needed or cause problems.

**Comment by nathanhammond** [comment]
@kfoisy It would be wonderful to have documentation for this–would you be willing to write it?

**Comment by kfoisy** [comment]
Yes. I'll try putting something together sometime next week.

**Comment by nathanhammond** [comment]
@kfoisy Thank you!

**Comment by kfoisy** [comment]
@nathanhammond I've created a pull request to add the documentation here: https://github.com/ember-cli/ember-cli.github.io/pull/109. Can you review the proposed documentation and let me know if any changes are needed?

Thanks!

**Comment by kfoisy** [comment]
@nathanhammond the pull request has been merged in, so I think this can be closed now.
