### ISSUE TITLE
app.import outputFile is not documented

### ISSUE THREAD

**Issue by ro0gr** [ember-cli/ember-cli.github.io#104]
[rfc](https://github.com/ember-cli/rfcs/blob/master/complete/0000-app-import-output-file.md) is completed but [people can't find](https://github.com/ember-cli/ember-cli/issues/3760#issuecomment-260075903) any related documentation yet.

I think at least few words about `outputFile` in the docs have to be said.

**Comment by nathanhammond** [comment]
Looks good to me! Thank you for your attention to detail and improving our documentation!
