### ISSUE TITLE
Named AMD asset import example is wrong

### ISSUE THREAD

**Issue by carlbennettnz** [ember-cli/ember-cli.github.io#116]
https://ember-cli.com/user-guide/#standard-amd-asset

> Provide the asset path as the first argument, **and the list of modules and exports as the second**:
> `app.import('bower_components/ic-ajax/dist/named-amd/main.js');`

Looks like the second argument was missed.

**Comment by stefanpenner** [comment]
@carlbennettnz for named amd, no second argument is needed. For anonymous AMD it is.

**Comment by carlbennettnz** [comment]
Ah ok. Is it worth adding a note to that section explaining the difference and giving an example of unnamed? I wouldn't know how to do unnamed with what's there.

**Comment by kellyselden** [comment]
> Is it worth adding a note to that section explaining the difference and giving an example of unnamed?

Yes. It doesn't look like there's an example of anonymous AMD import yet.

**Comment by kellyselden** [comment]
Resolved in #122
