### ISSUE TITLE
VSCode Editor

### ISSUE THREAD

**Issue by m-nagy** [ember-cli/ember-cli.github.io#119]
I think we should add [VSCode](https://code.visualstudio.com/) to editors list.
It has extensions for supporting EmberCLI and handlebars
[Ember Cli in Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=felixrieseberg.vsc-ember-cli)
[Ember JS (ES6) and Handlebars code snippets](https://marketplace.visualstudio.com/items?itemName=phanitejakomaravolu.EmberES6Snippets)
[Ember Colorizer and Theme](https://marketplace.visualstudio.com/items?itemName=ciena-blueplanet.vsc-ember-frost)
[ember-addon-snippets](https://marketplace.visualstudio.com/items?itemName=ciena-blueplanet.ember-addon-snippets)
[Handlebars](https://marketplace.visualstudio.com/items?itemName=andrejunges.Handlebars)

And we can enable handlebars indention option through `html.format.indentHandlebars` setting

**Comment by kellyselden** [comment]
No complaint here :)

**Comment by nathanhammond** [comment]
Closing this as an issue, @m-nagy please open a PR!
