### ISSUE TITLE
Docs recommend watcman 3.x, but 4.x is the latest stable

### ISSUE THREAD

**Issue by williamhaley** [ember-cli/ember-cli.github.io#134]
On linux, I was getting annoyed by the `Could not start watchman` warning from ember-cli that appears after running `ember serve` so I decided to install watchman to give it a whirl.

The [ember-cli docs](https://ember-cli.com/user-guide/#watchman) say "we recommend installing Watchman version 3.x, which provides Ember CLI a more effective way for watching project changes."

However, the [watchman docs](https://facebook.github.io/watchman/docs/install.html) instruct users to `git checkout v4.7.0  # the latest stable release`

Are the ember-cli docs out of date? In which case, I'm guessing that 3.x should be updated to 4.x.

Or are ember-cli users supposed to purposefully use an older build of watchman? In which case it might be worth calling that out in the docs.

**Comment by stefanpenner** [comment]
thanks! https://github.com/ember-cli/ember-cli.github.io/pull/135

**Comment by stefanpenner** [comment]
> Or are ember-cli users supposed to purposefully use an older build of watchman? In which case it might be worth calling that out in the docs.

just outdated docs

**Comment by williamhaley** [comment]
Awesome! Thanks for clarifying.
