### ISSUE TITLE
Add yarn to upgrade instructions on Release notes

### ISSUE THREAD

**Issue by Caltor** [ember-cli/ember-cli.github.io#140]
The release notes at https://github.com/ember-cli/ember-cli/releases specify how to upgrade using `npm`. Shouldn't this be changed for `yarn` now or at least instructions for `yarn` added?

**Comment by rwjblue** [comment]
Yes, we should also add `yarn` instructions.

**Comment by locks** [comment]
Moved to https://github.com/ember-cli/ember-cli/issues/7704.
