### ISSUE TITLE
Creating a new add-on: no components are created automatically

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-cli.github.io#143]
It is my first time creating an ember add-on.  
The docs @ [https://ember-cli.com/extending/#addon-components](https://ember-cli.com/extending/#addon-components) assume that the `addon/components/x-button.js` file is already created; it is not.

Do you have to run `ember g component x-button`?  
It'd be useful to have this in the docs.

**Comment by stefanpenner** [comment]
> Do you have to run ember g component x-button?

Yup.

Would you mind proposing the change [here](https://github.com/ember-cli/ember-cli.github.io/edit/master/_posts/2013-04-06-developing-addons-and-blueprints.md) that way we can get it in a better shape together.

**Comment by stefanpenner** [comment]
thanks for the docs update :)
