### ISSUE TITLE
[Documentation] Node dependency should be LTS version

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli.github.io#154]
See https://ember-cli.com/#node

> Currently, Ember CLI supports Node (4.0 recommended) and npm (2.x).

Perhaps the support should refer to the LTS version of Node and NPM, and link to info on the Node LTS versions?

**Comment by stefanpenner** [comment]
Totally agree! Got a sec to update?

**Comment by jeffjewiss** [comment]
Should this be closed? Looks like it's already been updated to:

> Currently, Ember CLI supports Node (latest LTS recommended), npm (3.x and above) or yarn.
