### ISSUE TITLE
Thoughts regarding suggested links for 'tutorials'

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli/ember-cli.github.io#159]
There are a great many Ember resources at this point, and the list we have here isn't a fair slice of those. A few of them are not currently up to date + some are free and some are paid - and in general, it seems too random. Are these suggested tutorials for CLI specific things? I think it would be hard to officially recommend Something like rock-and-roll vs mike's front-end-masters courses - let alone the other 12 or so resources / from $0 to $2k. I don't have a solution, but I wanted to bring it up. Either we build an extensive list to use across ember properties / or link to some outside list / or just leave it up to Google.

Either way, the official learning resources should be here. I'm not sure what the best URL is though: https://guides.emberjs.com/v2.14.0/getting-started/quick-start/ vs https://guides.emberjs.com/quick-start and https://guides.emberjs.com/tutorial (it would be great to have a 'latest' URL that was easy to remember)

Maybe It could link to something like this: https://github.com/nmec/awesome-ember for a more comprehensive list that is maintained by someone else / otherwise it seems like we'd have a duty to check the supported version of each resource.

The only other suggestion is that tooling is moved up in the hierarchy.

I meant to create an 'issue' / but I'm foggy: #158

**Comment by stefanpenner** [comment]
I'm always nervous to link to for-pay training (it gets complicated with OSS projects). But i do agree @mike-north has some great material. Maybe he has a recommendations on this topic?

**Comment by locks** [comment]
Partially addressed by #158.
