### ISSUE TITLE
Should we recommend installing phantomjs2 without using npm?

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli.github.io#18]

**Comment by stefanpenner** [comment]
> phantomjs2 or not using npm?

these seem orthogonal?

**Comment by Gaurav0** [comment]
I mean not installing phantomjs through npm.

**Comment by stefanpenner** [comment]
ah ok, yes I believe recommending a non npm based phantom installation to be a good idea.

**Comment by leo** [comment]
@Gaurav0 Why?

**Comment by Gaurav0** [comment]
On MacOSX and Linux, npm installed PhantomJS 1.9 through a prebuilt binary while it was possible to get PhantomJS 2.0 without going through npm. Now that PhantomJS 2.1 is available on npm, this is a less pressing issue. Now the only difference is whether sudo is used or not. Closing.
