### ISSUE TITLE
Add yarn instruction when in use with nvm

### ISSUE THREAD

**Issue by heat** [ember-cli/ember-cli.github.io#188]
Add YARN instruction when use nvm

I was in trouble when try to use yarn and nvm. Pop out this message:
```
Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
```
The solution came with this issue:

https://github.com/yarnpkg/yarn/issues/648#issuecomment-253162900

So I was wondering that is a good ember-cli setup topic , because yarn and nvm are in-fact stand.

**Comment by locks** [comment]
This isn't specific to `ember-cli`, so if you're using the `nvm` and `yarn` combo, you are likely to have come across it.
