### ISSUE TITLE
Add Docker files to help new contributors overcome dependency issues

### ISSUE THREAD

**Issue by jenweber** [ember-cli/ember-cli.github.io#193]
We've seen success in `guides` and `website` in offering some Docker setup. Contributors who have issues with the Ruby environment can still help out if they have a Dockerized build to fall back on.

Hoping @nullvoxpopuli can help or advise.

**Comment by NullVoxPopuli** [comment]
I can! I'll work on something tomorrow!

**Comment by NullVoxPopuli** [comment]
https://github.com/ember-cli/ember-cli.github.io/pull/194

**Comment by locks** [comment]
Can y'all review?

**Comment by acorncom** [comment]
Works great, merged
