### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by maxwondercorn** [ember-cli/ember-cli.github.io#198]
The `npm-tricks` link under Developing Addons & Blueprints is broken.  Looks like devthought.com is gone.  I never saw the original page so I don't know what was covered.  I looked around for an alternative and found [this](https://medium.com/trisfera/the-magic-behind-npm-link-d94dcb3a81af) on Medium.  

There might be something better but my research didn't find a lot of resources around npm linking.

**Comment by JoaoGFarias** [comment]
[HTML-proofer](https://github.com/gjtorikian/html-proofer#using-with-jekyll) can catch this kind of error on CI.
