### ISSUE TITLE
Asset compilation section should mention how to uninstall babel

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli.github.io#20]

**Comment by stefanpenner** [comment]
do you mean ember-cli-babel? because ember-cli always will use babel internally...

**Comment by Gaurav0** [comment]
Yes. So if someone were using CoffeeScript, wouldn't they have to remove that from package.json?

**Comment by stefanpenner** [comment]
> Yes. So if someone were using CoffeeScript, wouldn't they have to remove that from package.json?

I'm inclined to say that is the responsibility of the docs in the coffee-script / emberscript readme.

Ultimately anything in the package.json blueprint is optional, removing it will remove its associated functionality. Which someone may or may not want, but it is available to them. I don't think special cases ember-cli-babel in the ember-cli docs makes sense.

**Comment by leo** [comment]
IMHO, @stefanpenner is right.
