### ISSUE TITLE
Create `releases` or `upgrade` button on main page

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli.github.io#209]
Problem:

each time when I want to update ember-cli I do:
* go to ember-cli.com
* - struggle to find a step-by-step upgrade guide
* go to google.com
* - type "ember cli update", 
* - clicking on second search result
* - profit!

https://github.com/ember-cli/ember-cli/releases

How it may be:
* go to ember-cli
* click on 'updates' button

**Comment by lolmaus** [comment]
Actually, there is a valid path on ember-cli.com. Starting on the root page:
* Guide
* Upgrading
* release notes for each release

If you already know that step-by-step release guides are on GitHub, you can take a shorter path. Starting on ember-cli.com root page:
* Contributing (takes you to GitHub)
* Releases

But if you're really desperate, you can simply click the version number, which takes you directly to releases:

![image](https://user-images.githubusercontent.com/200884/38674492-4eb2eb06-3e5d-11e8-8b7f-2401eda8d2fa.png)

**Comment by lifeart** [comment]
@lolmaus thank you for this findings! I'm think it will be better to highlight `Version 3.1.1` as link or create small text near `Version 3.1.1`  -> `Version 3.1.1 notes`
