### ISSUE TITLE
Update docs for troubleshooting memory errors, failed to stat, and slow build times

### ISSUE THREAD

**Issue by danDanV1** [ember-cli/ember-cli.github.io#213]
Seems that the ./tmp folder can get corrupted and then ember app fails to start via ember-cli, throwing broccoli errors, out of memory, and extremely slow build times.

eg. 
`Warning: failed to stat /..../tmp/broccoli_merge_trees-input_base_path-0GVrVmJW.tmp/10/.gitkeep`

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

Fix is to clear the ./tmp folder. 

See the following issue for confirmation of bug occurrence and fix. 
https://github.com/ember-cli/ember-cli/issues/7392#issuecomment-391828332

Costs of developer time to diagnose is quite large.

**Comment by rwjblue** [comment]
Do you mean `/tmp` or `./tmp`?

**Comment by danDanV1** [comment]
My apologies `./tmp` local to the ember app.
