### ISSUE TITLE
Change guide link from index page to go to new guides

### ISSUE THREAD

**Issue by yarigpopov** [ember-cli/ember-cli.github.io#221]
I recently tried to find our new guides for ember-cli and it took me 2 hours. In the end I noticed  a hero on the getting started page. https://ember-cli.com/user-guide/

I believe this is not very noticeable and many people are missing it. How about to be more radical here and change the"guide" link on the page https://ember-cli.com/  to go to the new guide(https://cli.emberjs.com/release/)? And put hero for old version there

**Comment by acorncom** [comment]
With the new header at the top do you think we’re handling your issue well enough? Believe the desire was to avoid breaking old links while steering folks to the new site

**Comment by rwjblue** [comment]
Ya, I think that we should essentially decommission this repo and have ember-cli.com redirect to cli.emberjs.com.

Thoughts @jenweber?
