### ISSUE TITLE
missing exo-light-webfont font, broken pre styles

### ISSUE THREAD

**Issue by bgentry** [ember-cli/ember-cli.github.io#44]
I'm seeing a missing font on http://ember-cli.com/user-guide/ 

```
Request URL:http://ember-cli.com/assets/fonts/exo-light-webfont.woff2
Request Method:GET
Status Code:404 Not Found
Remote Address:192.30.252.154:80
```

Also, the code samples are all black (tried in Chrome and Safari, even w/out ad blockers!):

<img width="1433" alt="screen shot 2016-02-03 at 9 10 52 pm" src="https://cloud.githubusercontent.com/assets/114033/12806416/b70b6d5e-caba-11e5-8381-4b1516e33493.png">

**Comment by trabus** [comment]
The `2` makes me think there's somehow a duplicate font asset being expected, but I'm not quite familiar with jekyll, so I'm not sure how it would be happening. Anyhow, `assets/fonts/exo-light-webfont.woff2` doesn't exist `assets/fonts/exo-light-webfont.woff` does.

**Comment by tsing80** [comment]
the second issue is not related to the fonts. somehow both the foreground and background color is set to black so the word cannot be seen

**Comment by trabus** [comment]
Something went sideways, the question is has it been this way since the last merge 13 hours ago?

**Comment by leo** [comment]
Will fix this! Give me a second.

**Comment by leo** [comment]
Wasn't related to the missing font, but rather to the line numbers converting some code samples into weird table markup that hasn't been styled yet. Fixed both in 899dbf750bbe3a2363dcf70e6f0fe7e7b1612d32.

Please confirm that it's working now :blush:

**Comment by trabus** [comment]
@leo Thanks! It appears to be resolved.
@bgentry please reopen if you find otherwise. Thanks for reporting!

**Comment by bgentry** [comment]
everything looks good, thanks!
