### ISSUE TITLE
Code samples unreadable at : http://ember-cli.com/user-guide/#naming-conventions

### ISSUE THREAD

**Issue by shearichard** [ember-cli/ember-cli.github.io#45]
All of the code samples at http://ember-cli.com/user-guide/#naming-conventions are blackish text on a blackish background .

**Comment by trabus** [comment]
Closing, this appears to be a duplicate of #44 I'm guessing the missing font is somehow related.

**Comment by leo** [comment]
Sadly not a duplicate.

**Comment by shearichard** [comment]
Excellent ! Thanks for doing the fix.
