### ISSUE TITLE
Add section for using CLI without Ember

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli.github.io#48]
Came up in slack. References:
https://www.smashingmagazine.com/2016/01/write-next-web-app-ember-cli/#not-just-for-ember
https://github.com/mozilla/ember-cli-fxos
https://github.com/angular/angular-cli

**Comment by locks** [comment]
https://github.com/candycanejs/candycane-cli

**Comment by leo** [comment]
Question: Why are we supporting other frameworks by allowing them to use "our" CLI? I mean, the reason why Ember still exists is because its users don't fully like how other frameworks work. If they would, they could just use those. So why are you guys planning to support them?

**Comment by kellyselden** [comment]
@leo It's a win/win scenario. they get a great, already built cli, we get upstream features and fixes. The people I know and work with on the various Ember teams don't care about "market share", just trying to build cool, useful stuff.

**Comment by john-griffin** [comment]
This issue just came up when googled "ember cli without ember". Has anyone put together a guide for this or have any pointers?
