### ISSUE TITLE
document app.import constraints

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli.github.io#52]
"app.import doesn't work for files outside vendor and bower_components folder " from here https://github.com/ember-cli/ember-cli/issues/3890#issuecomment-186293335

**Comment by stavarotti** [comment]
@kellyselden, since this is already documented ([Managing Dependencies](http://ember-cli.com/user-guide/#managing-dependencies)), perhaps making the section more prominent will help future travelers?

**Comment by pixelhandler** [comment]
@kellyselden @stavarotti I think there needs to be a note that you cannot `app.import` from a path using `node_modules`.

**Comment by runspired** [comment]
I opened an RFC issue to discuss a solution for importing from node_modules: https://github.com/ember-cli/rfcs/issues/84

**Comment by stefanpenner** [comment]
@runspired `app.import` does not important from `node_modules` (likely something that should be documented)

**Comment by runspired** [comment]
@stefanpenner confirm, I think we should work out a way for it to in the future, or better yet, build a "resolvedVendor" tree of npm modules based on otherwise unfound imports

**Comment by locks** [comment]
Tracked at https://github.com/emberjs/guides/pull/2296.
