### ISSUE TITLE
addAddonToProject is undocumented

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli.github.io#57]
ripe for new contributors

**Comment by kellyselden** [comment]
Also the companion `addAddonsToProject` is missing too.

**Comment by bugduino** [comment]
+1

**Comment by RobbieTheWagner** [comment]
@kellyselden is there a section in the docs this should be added in?

**Comment by nathanhammond** [comment]
@rwwagner90 Literally anywhere. 😜 We aren't going to be picky on getting new information into the guides. We can organize it later.

**Comment by RobbieTheWagner** [comment]
@nathanhammond I've just never contributed to the guides, so I have no idea where to attempt to put it.

**Comment by kellyselden** [comment]
@rwwagner90 in the creating an addon section. Somewhere in here https://ember-cli.com/extending/#default-blueprint . maybe a new section "Working with dependencies"

**Comment by RobbieTheWagner** [comment]
I threw up a PR with an attempt at documentation. Please let me know if you would like any changes made.
