### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli.github.io#58]
Two things:
- [x] I've noticed that you're copying the changelog to this repo each time a new version gets released. In my opinion, we could just link "Changelog" to [this page](https://github.com/ember-cli/ember-cli/releases) (Google also doesn't like duplicated content on the web, btw).
- [x] I also think that we should remove the version tag from the site. If you don't want to do that, let's just use jQuery to get the latest version from the first element [here](https://github.com/ember-cli/ember-cli/tags) and insert it into the site (will probably add a slight delay).

What do you think? @stefanpenner @rwjblue

**Comment by stefanpenner** [comment]
Ya we could link to releases instead of copying the change log.

As for the version, we should likely still have it. Although we could automate it as part of the actual release

**Comment by leo** [comment]
> Ya we could link to releases instead of copying the change log.

Done in e86daf71b72747f6cbd150906c78b63914722339

> As for the version, we should likely still have it. Although we could automate it as part of the actual release

Let's say I would add some JavaScript to load the latest version from the "Tags" page, would you be fine with that?

**Comment by stefanpenner** [comment]
I believe so. As long as it doesn't pop-in. So clean UX and I'm fine if the response for version is somewhat latent

**Comment by leo** [comment]
@stefanpenner http://ember-cli.com ? :blush: (9973145670da352a694db97b2fd068ee710c473c)

**Comment by rwjblue** [comment]
@leo - All changes should go through pull requests, so we have a chance to review.

**Comment by stefanpenner** [comment]
what @rwjblue said, but it looks pretty good. Would -.-.- > 2.4.3 transition (instead of 0.0.0 -> x.y.z) look better or worse

**Comment by rwjblue** [comment]
Can you also update `RELEASE.md` with the new steps (really just removing the steps that are not needed now)?

**Comment by leo** [comment]
@rwjblue Stefan told me that at the beginning. Sorry, I simply thought the change isn't big enough for opening a PR. And yep, I'll adjust `RELEASE.md` now :blush:

@stefanpenner Worse, if you ask me: http://d.pr/v/m0gm

**Comment by stefanpenner** [comment]
@leo yup totally worse, 0.0.0 looks good :shipit:

**Comment by stefanpenner** [comment]
> I'll adjust RELEASE.md now

thanks
