### ISSUE TITLE
Cannot see Overview on Ember CLI Home page

### ISSUE THREAD

**Issue by baron1405** [ember-cli/ember-cli.github.io#64]
Using Chrome 49 on Mac OSX 10.10.5, cannot see the overview page/pane when clicking on the Overview button. Click on Overview and nothing happens. Scroll the page and you see some of the Overview but it is covered over by the home page.

**Comment by stefanpenner** [comment]
Cc @leo

**Comment by akashdsouza** [comment]
Removing `position: absolute` in #showcase fixes this. However, not sure if this is the right solution. If this is the right way to go, will be happy to submit a PR

**Comment by leo** [comment]
@baron1405 Fixed now?

**Comment by baron1405** [comment]
Fixed, thanks!
