### ISSUE TITLE
Home page still shows version 0.0.0

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli.github.io#66]
Originally created by @baron1405:

> Using Chrome 49 on Mac OSX 10.10.5, the Ember CLI home page shows the current version of Ember CLI as 0.0.0. I had opened this issue previously and thought it was fixed but I think that was transient.

**Comment by leo** [comment]
@baron1405 Fixing the layout issue might also have solved this one. Can you confirm that it works now (please clear your cache before reloading)?

**Comment by baron1405** [comment]
Unfortunately, even with the layout fix and a cleared cache, I still see 0.0.0

**Comment by leo** [comment]
@baron1405 Can you show us the output of your browser's console?

**Comment by stefanpenner** [comment]
@baron1405 does your request to:

```
https://api.github.com/repos/ember-cli/ember-cli/releases/latest
```

remain pending or... 
Are there any console errors?

**Comment by leo** [comment]
Might be caused by an extension: https://bugs.chromium.org/p/chromium/issues/detail?id=360583

**Comment by leo** [comment]
@baron1405 Did you check it?

**Comment by leo** [comment]
Just tested this again on all kinds of browsers and wasn't able to find a bug. As I said, it's probably related to an extension, therefore closing this now.

@baron1405 Please disable your extensions and try reloading the page. If that doesn't work, please drop another comment in here.

**Comment by stefanpenner** [comment]
Sound reasonable. Thanks for digging in :)
