### ISSUE TITLE
Generator options

### ISSUE THREAD

**Issue by SpikedKira** [ember-cli/ember-cli.github.io#78]
http://ember-cli.com/extending/#generators-and-blueprints

"The afterInstall and afterUninstall hooks receives the same arguments as locals"

"ember generate controller foo --type=array --dry-run"
"The object passed to locals looks like this:"

```
{
  entity: {
    name: 'foo',
    options: {
      type: 'array'
    }
  },
  dryRun: true
}
```

I believe options.entity.options is incorrect.
Seems like I am receiving:

```
{
  entity: {
    name: 'foo'
  },
  dryRun: true,
  type: 'array'
}
```

**Comment by maxwondercorn** [comment]
I'm helping port the blueprints section from the old ember-cli guide to the new one and verifying the examples as I go through the guide. Came across the same issue.

Something like ` ember generate controller foo isAdmin:true --type=array --dry-run`
generates an object that's closer to the intent of the example

```    
{
 entity: {
    name: 'foo',
     options: {
        isAdmin: true
     }
  },
  dryRun: true
  type: 'array'
 }
```
If desired, I can create a PR based on my alternate example or something similar.   I'll have a few more issues related to things I've found while reviewing the guides

Edited:  actually this should be an issue with on ember-cli to update the code comments.  The new guides will be corrected as they are created.
