### ISSUE TITLE
Documentation seems outdated on using a different build than release

### ISSUE THREAD

**Issue by remkoboschker** [ember-cli/ember-cli.github.io#79]
The documentation reads that a ember-data release channel can be chosen in the bower.json. I believe ember-data is now an ember-addon installed via npm. Also I would like to know how I can define using the long term support release channels for ember and ember-data. Do they still exist?

```
Using canary build instead of release

In bower.json instead of a version number use:

"ember": "components/ember#canary",
And, following dependencies add resolutions:

"resolutions": {
  "ember": "canary"
}
This can also be applied to Ember Data:

"ember-data": "components/ember-data#canary",
And, adding to resolutions:

"resolutions": {
  "ember-data": "canary"
}
```

**Comment by nruth** [comment]
It'd be great to also cover using ember LTS here.

**Comment by jacobq** [comment]
Are there currently any plans to show docs for multiple versions on the site, similar to the [Ember API docs](https://emberjs.com/api/ember/)?
