### ISSUE TITLE
EmberCli logo on site appears to be missing the ®

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli.github.io#82]
http://emberjs.com/logos/ contains a link to a zip with http://emberjs.com/images/brand/logos-ember.zip which contains the correct variant of the logo \w the registered trade-mark

**Comment by stefanpenner** [comment]
@leo thanks leo, i noticed that the configuration of logo (white CLI + transparent background) isn't one of the ones available by default (although could be crafted) or I would have just swapped them myself.

**Comment by leo** [comment]
@stefanpenner No problem! Not much work.

**Comment by leo** [comment]
Done! Please note that the orange color of previous one was a little lighter, but I didn't adjust the color of the new one because:

> ...may not be manipulated in any way...

**Comment by stefanpenner** [comment]
@leo awesome thank you very much!
