### ISSUE TITLE
specify exports when calling app.import

### ISSUE THREAD

**Issue by luxzeitlos** [ember-cli/ember-cli.github.io#84]
[here](https://ember-cli.com/user-guide/#standard-amd-asset) it is documented to specify `exports` when calling app.import. However It [looks like this is not implemented](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1487) nor documented anywhere else.

Also its not clear what it should do. Calling `app.import('...js')` does, as far as I know, just add the file to the vendor.js. So if AMD modules are defined they should just work. Why should they be explicit declared?

**Comment by stefanpenner** [comment]
it doesn't do anything.

**Comment by luxzeitlos** [comment]
@stefanpenner Shouldn't it then be removed from the website?

**Comment by leo** [comment]
IMHO, it should be removed then. @stefanpenner?

**Comment by stefanpenner** [comment]
> IMHO, it should be removed then. @stefanpenner?

yup
